data:
  name: car
  file_path: conditional-monge/CD8.h5ad
  drugs_path: conditional-monge/CAR_variants.txt
  features: conditional-monge/functional_and_score_genes.txt
  batch_size: 256
  split: [0.8, 0.2, 0]
  drug_col: CAR_Variant
  drug_condition: IL15RA-CD28-z
  control_condition: NA-NA-NA
  ae: false
  seed: 42

condition:
  mode: homogeneous
  conditions: [IL15RA-CD40-z, CD40-CD40-z, CD40-NA-z, IL15RA-41BB-z, IL15RA-CTLA4-z, IL15RA-NA-z, CD28-NA-z, 41BB-IL15RA-z, 41BB-NA-z, CD40-CD28-z, CD28-IL15RA-z, CD28-CD28-z, IL15RA-CD28-z, 41BB-41BB-z]
  split: [0.8, 0.2, 0]

model:
  method: monge

  fitting_loss:
    name: sinkhorn
    kwargs:
      epsilon_fitting: 1

  regularizer:
    name: monge
    kwargs:
      epsilon_regularizer: 1.0e-2
      cost: euclidean

  optim:
    lr: 1.0e-4
    grad_acc_steps: 1
    name: adamw
    kwargs:
      weight_decay: 1.0e-5
  mlp:
    dim_hidden: [64, 64, 64, 64]
    dim_data: 82
    dim_cond: 5120
    dim_cond_map: 50
    layer_norm: false

  embedding:
    name: esm2_t48_15B_UR50D_tail_dim
    model_dir: conditional-monge/embedding
    checkpoint: true
  
  num_train_iters: 10000
  seed: 42
